version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  post_build:
    commands:
      - aws cloudformation package
        --template-file function.yml
        --s3-bucket ${S3_BUCKET}
        --output-template-file function.yml

artifacts:
  type: zip
  files:
    - function.yml
